# Generated by Django 5.0.6 on 2024-06-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevMeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('target', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('experienced', models.BooleanField()),
                ('level', models.IntegerField()),
                ('limitations', models.CharField(blank=True, max_length=255, null=True)),
                ('diet_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('day_commit', models.IntegerField()),
                ('exercise_preference', models.JSONField(blank=True, null=True)),
                ('any_supplement', models.BooleanField()),
                ('specify_supplement', models.JSONField(blank=True, null=True)),
                ('calo_per_day', models.IntegerField()),
                ('quality_sleep', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
