# Generated by Django 5.0.6 on 2024-06-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevMeApp', '0002_assessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_body_fat_percentage',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_duration_day',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_muscle_mass',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_weight',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='intensity_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sleep_quality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
        migrations.AddField(
            model_name='goal',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='bmi_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='daily_steps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='physical_activity_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='quality_of_sleep',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='sleep_disorder',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Insomnia', 'Insomnia'), ('Sleep Apnea', 'Sleep Apnea')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='stress_level',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
