# Generated by Django 5.0.6 on 2024-06-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevMeApp', '0004_remove_goal_blood_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
