# Generated by Django 5.0.6 on 2024-06-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevMeApp', '0008_alter_goal_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='family_history_w_overweight',
            new_name='family_history_with_overweight',
        ),
    ]
