# Generated by Django 5.0.6 on 2024-06-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevMeApp', '0010_exercise_meal_assessment_created_at_plan_mealplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
